server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://127.0.0.1:5500"
            allowedMethods: "*"
            allowedHeaders: "*"

      routes:
        - id: ingestion-service
          uri: lb://ingestion-service
          predicates:
            - Path=/api/ingestion/**
          filters:
            - StripPrefix=2

        - id: analytics-service
          uri: lb://analytics-service
          predicates:
            - Path=/api/analytics/**
          filters:
            - StripPrefix=2

        - id: database-service
          uri: lb://database-service
          predicates:
            - Path=/api/iocs/**
          filters:
            - StripPrefix=2

        - id: ranking-service
          uri: lb://ranking-service
          predicates:
            - Path=/api/ranking/**
          filters:
            - StripPrefix=2

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/