server:
  port: 8084

spring:
  application:
    name: ranking-service

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ranking-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/