server:
  port: 8086

spring:
  application:
    name: analytics-service

  kafka:
    bootstrap-servers: localhost:9092

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/